#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Windows 11" --class windows {
	insmod part_gpt
	insmod fat
	set root='(hd0,gpt1)'
	chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}
