-- ~/.config/hypr/hyprcolors.lua
-- Auto-generated by wallpaper_slideshow.sh
-- Do not edit manually; this file is overwritten whenever the wallpaper changes.

accent1 = "rgba(1a0d12ff)"
accent2 = "rgba(3767AFff)"
