-- ~/.config/hypr/hyprland.lua
-- Main Hyprland configuration (Lua)
-- Converted from your hyprland.conf and updated to use Lua modules.

----------------------------------------------------------------------
-- Core configuration
----------------------------------------------------------------------

hl.config({
  autogenerated = false,
})

----------------------------------------------------------------------
-- Load modular Lua configuration files
-- These correspond to:
--   keyBind.conf        -> keyBind.lua
--   execute.conf        -> execute.lua
--   hyprwindowrule.conf -> hyprwindowrule.lua
--   hyprcolors.conf     -> hyprcolors.lua
----------------------------------------------------------------------

require("hyprColors")
require("execute")
require("hyprWindowRule")
require("keyBind")

----------------------------------------------------------------------
-- Environment variables
----------------------------------------------------------------------

hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XDG_MENU_PREFIX", "plasma-")

----------------------------------------------------------------------
-- Monitor configuration
----------------------------------------------------------------------

-- Equivalent to:
-- monitor = , preferred, auto, auto
hl.monitor({
  output = "",
  mode = "preferred",
  position = "auto",
  scale = "auto",
})

----------------------------------------------------------------------
-- Look and Feel / Core Configuration
----------------------------------------------------------------------

hl.config({
  general = {
    gaps_in = 3,
    gaps_out = 5,

    border_size = 3,

    -- Variables accent1 and accent2 are defined in hyprcolors.lua
    col = {
      active_border = {
        colors = { accent1, accent2 },
        angle = 45,
      },
      inactive_border = "rgba(595959aa)",
    },

    resize_on_border = false,
    allow_tearing = false,

    layout = "dwindle",
  },

  decoration = {
    rounding = 10,
    rounding_power = 2,

    active_opacity = 1.0,
    inactive_opacity = 1.0,

    shadow = {
      enabled = true,
      range = 4,
      render_power = 3,
      color = "rgba(1a1a1aee)",
    },

    blur = {
      enabled = true,
      size = 3,
      passes = 1,
      vibrancy = 0.1696,
    },
  },

  animations = {
    enabled = true,
  },

  dwindle = {
    -- pseudotile = true,
    preserve_split = true,
  },

  master = {
    new_status = "master",
  },

  misc = {
    force_default_wallpaper = 1,
    disable_hyprland_logo = false,
  },

  input = {
    kb_layout = "us",
    kb_variant = "",
    kb_model = "",
    kb_options = "",
    kb_rules = "",

    follow_mouse = 1,
    numlock_by_default = true,

    sensitivity = 0,

    touchpad = {
      natural_scroll = true,       -- Mac-style scrolling
      tap_to_click = true,         -- tap = click
      tap_and_drag = true,         -- tap-drag enabled
      clickfinger_behavior = true, -- multi-finger click enabled
      disable_while_typing = true, -- optional, prevents accidental touches
    }
  },
})

----------------------------------------------------------------------
-- Animation Curves
----------------------------------------------------------------------

hl.curve("easeOutQuint", {
  type = "bezier",
  points = {
    { 0.23, 1 },
    { 0.32, 1 },
  },
})

hl.curve("easeInOutCubic", {
  type = "bezier",
  points = {
    { 0.65, 0.05 },
    { 0.36, 1 },
  },
})

hl.curve("linear", {
  type = "bezier",
  points = {
    { 0, 0 },
    { 1, 1 },
  },
})

hl.curve("almostLinear", {
  type = "bezier",
  points = {
    { 0.5,  0.5 },
    { 0.75, 1 },
  },
})

hl.curve("quick", {
  type = "bezier",
  points = {
    { 0.15, 0 },
    { 0.1,  1 },
  },
})

----------------------------------------------------------------------
-- Animation Definitions
----------------------------------------------------------------------

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })

----------------------------------------------------------------------
-- Gestures
----------------------------------------------------------------------

hl.gesture({
  fingers = 3,
  direction = "horizontal",
  action = "workspace",
})

----------------------------------------------------------------------
-- Per-device Settings
----------------------------------------------------------------------

hl.device({
  name = "epic-mouse-v1",
  sensitivity = -0.5,
})

----------------------------------------------------------------------
-- Gestures
----------------------------------------------------------------------

--  hl.gesture({
--  fingers = 3,
--  direction = "horizontal",
--  action = "workspace",
-- }) ]]
----------------------------------------------------------------------
-- Per-device settings
----------------------------------------------------------------------



----------------------------------------------------------------------
-- Built-in window rules from your original config
----------------------------------------------------------------------

hl.window_rule({
  name = "windowrule-1",
  suppress_event = "maximize",
  match = {
    class = ".*",
  },
})

hl.window_rule({
  name = "windowrule-2",
  no_focus = true,
  match = {
    class = "^$",
    title = "^$",
    xwayland = 1,
    float = 1,
    fullscreen = 0,
    pin = 0,
  }
})

----------------------------------------------------------------------
-- HyprEmoji (still using legacy Hyprlang for now)
-- Convert this later if desired.
----------------------------------------------------------------------

-- hl.source("~/.config/hypremoji/hypremoji.conf")
