-- ~/.config/hypr/hyprcolors.lua
-- Auto-generated by wallpaper_slideshow.sh
-- Do not edit manually; this file is overwritten whenever the wallpaper changes.

accent1 = "rgba(0C0606ff)"
accent2 = "rgba(D89165ff)"
