-- ~/.config/hypr/hyprcolors.lua
-- Auto-generated by wallpaper_slideshow.sh
-- Do not edit manually; this file is overwritten whenever the wallpaper changes.

accent1 = "rgba(180a1cff)"
accent2 = "rgba(AD4D49ff)"
