#!/bin/bash
dir="$HOME/scripts"
# Define the default source file
DEFAULT_SOURCE="$dir/ascii-art.txt"
# Set the initial source to the default
SOURCE="$DEFAULT_SOURCE"

# Check for the --cus option and set the source file accordingly
case "$1" in
  --help)
      echo "Usage: $0 {kw|ag|sa}"
      exit 1
      ;;
    kw)
      SOURCE="$dir/ascii-kw.txt"
      ;;
    kw2)
      SOURCE="$dir/ascii-kw2.txt"
      ;;
    kw3)
      SOURCE="$dir/ascii-kw3.txt"
      ;;
    ag)
      SOURCE="$dir/ascii-ahegao.txt"
      ;;
    ag2)
      SOURCE="$dir/ascii-ahegao2.txt"
      ;;
    ag3)
      SOURCE="$dir/ascii-ahegao3.txt"
      ;;
    ag4)
      SOURCE="$dir/ascii-ahegao4.txt"
      ;;
    sa)
      SOURCE="$dir/ascii-saitama.txt"
      ;;
    lw)
      SOURCE="$dir/ascii-luffy-wanted.txt"
      ;;
    lu)
      SOURCE="$dir/ascii-luffy.txt"
      ;;
    he)
	    SOURCE="$dir/ascii-hen.txt"
	    ;;
    he2)
	    SOURCE="$dir/ascii-hen2.txt"
      ;;
    he3)
      SOURCE="$dir/ascii-hen3.txt"
      ;;
      *)
    esac

# Run neofetch with the selected source file
clear & fastfetch --logo "$SOURCE" --logo-position left
